apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-kafdrop-production
resources:
  - namespace.yaml
  - ../../base/kafdrop
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml